# Gopkg.toml
#
# Doc https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "~0.11.5"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
